######################################################################
# Automatically generated by qmake (2.01a) ma jul. 16 16:19:52 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += convert_merc.cpp
